### ISSUE TITLE
Drag'n drop zip directory with strange files produces error

### ISSUE THREAD

**Issue by lepenkinya** [enslinmike/Typing-freeze-analyzer#2]
![image](https://cloud.githubusercontent.com/assets/1558356/20882719/583e209e-baf3-11e6-85db-89936fc86f02.png)

**Comment by enslinmike** [comment]
what exactly did you drop ?

**Comment by lepenkinya** [comment]
Some random zip with pdfs found in my "Downloads" directory :)

пн, 5 дек. 2016 г. в 17:42, Mikhail Nasimov <notifications@github.com>:
